[tools]
node = "latest"
"npm:biome" = "latest"
"npm:pnpm" = "latest"
"npm:typescript" = "latest"

[env]
NODE_ENV = "development"
# '_'.file = ".env"

[plugins]

[settings]
status.missing_tools = "if_other_versions_installed"
status.show_env = true
status.show_tools = true
